// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title L2StateCore_Scam
/// @notice Minimal L1 settlement contract for zk-STARK-proven computation
contract L2StateCore_Scam {
    /// @notice Last verified result (e.g. 500th prime)
    uint256 public lastVerifiedPrime;

    event StateUpdated(uint256 prime);

    /// @dev Placeholder verifier
    /// In a real setup, this would call a STARK verifier contract
    function _verifyProof(
        bytes calldata proof,
        uint256 claimedPrime
    ) internal pure returns (bool) {
        // MVP rule:
        // - proof exists
        // - claimedPrime > 0
        return proof.length > 0 && claimedPrime > 0;
    }

    /// @notice Submit a zk-STARK proof for the prime computation
    /// @param proof zk-STARK proof generated by STWO
    /// @param claimedPrime Output of the Cairo/Rust program
    function updateState(
        bytes calldata proof,
        uint256 claimedPrime
    ) external {
        require(
            _verifyProof(proof, claimedPrime),
            "Invalid zk proof"
        );

        lastVerifiedPrime = claimedPrime;
        emit StateUpdated(claimedPrime);
    }
}
