// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "./IVerifier.sol";

/// @title L2StateCore_example
/// @notice Minimal L1 settlement contract for zk-STARK-proven computation
contract L2StateCore_example {
    /// @notice Last verified result (e.g. 500th prime)
    uint256 public lastVerifiedPrime;

    /// @notice zk-STARK verifier contract
    IVerifier public verifier;

    event StateUpdated(uint256 prime);

    constructor(address verifierAddress) {
        verifier = IVerifier(verifierAddress);
    }

    /// @notice Submit a zk-STARK proof for the prime computation
    /// @param proof zk-STARK proof generated by STWO
    /// @param claimedPrime Output of the Cairo program
    function updateState(
        bytes calldata proof,
        uint256 claimedPrime
    ) external {
        require(
            verifier.verifyProof(proof, claimedPrime),
            "Invalid zk proof"
        );

        lastVerifiedPrime = claimedPrime;
        emit StateUpdated(claimedPrime);
    }
}
